# Generated by Django 5.2 on 2025-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
