# Generated by Django 5.2 on 2025-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testcase_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='key',
            field=models.CharField(default='default_key', max_length=200),
        ),
    ]
